### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fleapse** [jayvynl/django-clickhouse-backend#41]
**Describe the bug**
error when trying to apply migrations to another database

**To Reproduce**
I have 3 databases on my project:
default - pgsql
external - pgsql
clickhouse - clickhouse
I added clickhouse recently
before its addition there were models for the external pgsql database. migrations were applied without problems.
after adding the clickhouse - I added several models for it where there was a field with the DateTimeField type
I dropped data from an external database and wanted to apply old migrations with the command: python manage.py migrate --database=external , but got this traceback

**Expected behavior**
migrations must apply
**Versions**

- ClickHouse server version. 23.7.4.5
- Python version. 3.11.2
- Clickhouse-driver version. 0.2.6
- Django version. 4.1.9
- Django clickhouse backend version. 1.1.1

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/fleapse/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/fleapse/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/fleapse/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/fleapse/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/fleapse/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/fleapse/Projects/django_comments/manage.py", line 22, in <module>
    main()
  File "/home/fleapse/Projects/django_comments/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/db/migrations/executor.py", line 107, in migrate
    self.recorder.ensure_schema()
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/clickhouse_backend/patch/migrations.py", line 142, in ensure_schema
    editor.create_model(self.Migration)
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 444, in create_model
    sql, params = self.table_sql(model)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 216, in table_sql
    definition, extra_params = self.column_sql(model, field)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 348, in column_sql
    field_db_params = field.db_parameters(connection=self.connection)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 823, in db_parameters
    type_string = self.db_type(connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/clickhouse_backend/models/fields/base.py", line 76, in db_type
    self._check_backend(connection)
  File "/home/fleapse/.cache/pypoetry/virtualenvs/django-comments-CMNQPpe7-py3.11/lib/python3.11/site-packages/clickhouse_backend/models/fields/base.py", line 70, in _check_backend
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: DateTimeField must only be used with django clickhouse backend.
```
```python
class BaseRouter:
    external_route_app_labels = {"external"}
    clickhouse_route_app_labels = {"clickhouse"}

    def db_for_read(self, model, **hints):
        if model._meta.app_label in self.external_route_app_labels:
            return "external"
        if model._meta.app_label in self.clickhouse_route_app_labels:
            return "clickhouse"
        return "default"

    def db_for_write(self, model, **hints):
        if model._meta.app_label in self.external_route_app_labels:
            return "external"
        if model._meta.app_label in self.clickhouse_route_app_labels:
            return "clickhouse"
        return "default"

    def allow_relation(self, obj1, obj2, **hints):
        return True

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        if app_label == "external":
            return db == "external"
        if app_label == "clickhouse":
            return db == "clickhouse"
        if db == "external" or db == "clickhouse":
            return False
        return None

```

**Comment by Fleapse** [comment]
It’s worth adding that models for the external base are only in the external app, and for clickhouse - only in the clickhouse app

**Comment by Fleapse** [comment]
locally it was possible to apply the old migrations - after I commented out the clickhouse app in INSTALLED_APPS

**Comment by jayvynl** [comment]
Thank you, I will fix this soon.

**Comment by Hunter-99** [comment]
@jayvynl, when you will add release with this fix?

**Comment by jayvynl** [comment]
> @jayvynl, when you will add release with this fix?

In 1 or 2 days.

**Comment by jayvynl** [comment]
@Hunter-99 released as 1.1.2

**Comment by Hunter-99** [comment]
Great!

**Comment by Valeria-N** [comment]
@jayvynl, The same error occurred. The release is installed 1.1.2. Help, how to fix the error?
