### ISSUE TITLE
[QUESTION] DB::Exception: Syntax error: failed at position 268 ('<'): <clickhouse_backend.models.fields.integer.UInt64Field>

### ISSUE THREAD

**Issue by LHLHLHE** [jayvynl/django-clickhouse-backend#75]
Is there any way to view the query that is generated during migrations?

I get this error when I try to apply migrations and want to understand what's the matter:

```
2024-02-06 15:11:23 Traceback (most recent call last):
2024-02-06 15:11:23   File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/dbapi/cursor.py", line 111, in execute
2024-02-06 15:11:23     response = execute(
2024-02-06 15:11:23                ^^^^^^^^
2024-02-06 15:11:23   File "/usr/local/lib/python3.11/site-packages/clickhouse_backend/driver/client.py", line 53, in execute
2024-02-06 15:11:23     rv = self.process_ordinary_query(
2024-02-06 15:11:23          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-06 15:11:23   File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 571, in process_ordinary_query
2024-02-06 15:11:23     return self.receive_result(with_column_types=with_column_types,
2024-02-06 15:11:23            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-06 15:11:23   File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 204, in receive_result
2024-02-06 15:11:23     return result.get_result()
2024-02-06 15:11:23            ^^^^^^^^^^^^^^^^^^^
2024-02-06 15:11:23   File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/result.py", line 50, in get_result
2024-02-06 15:11:23     for packet in self.packet_generator:
2024-02-06 15:11:23   File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 220, in packet_generator
2024-02-06 15:11:23     packet = self.receive_packet()
2024-02-06 15:11:23              ^^^^^^^^^^^^^^^^^^^^^
2024-02-06 15:11:23   File "/usr/local/lib/python3.11/site-packages/clickhouse_driver/client.py", line 237, in receive_packet
2024-02-06 15:11:23     raise packet.exception
2024-02-06 15:11:23 clickhouse_driver.errors.ServerException: Code: 62.
2024-02-06 15:11:23 DB::Exception: Syntax error: failed at position 268 ('<'): <clickhouse_backend.models.fields.integer.UInt64Field>)). Expected one of: literal, NULL, number, Bool, true, false, string literal, SELECT query, possibly with UNION, list of union elements, SELECT query, subquery, possibly with UNION, SELECT subquery, SELECT query, WITH, FROM, SELECT, EXPLAIN, token, Comma, ClosingRoundBracket, CAST operator, NOT, INTERVAL, CASE, DATE, TIMESTAMP, tuple, collection of literals, array, asterisk, qualified asterisk, compound identifier, list of elements, identifier, COLUMNS matcher, COLUMNS, qualified COLUMNS matcher, substitution, MySQL-style global variable, end of query. Stack trace:
2024-02-06 15:11:23 
2024-02-06 15:11:23 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c07e5a8 in /usr/bin/clickhouse
2024-02-06 15:11:23 1. DB::Exception::createDeprecated(String const&, int, bool) @ 0x0000000007aa41c0 in /usr/bin/clickhouse
2024-02-06 15:11:23 2. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, String const&, bool, unsigned long, unsigned long) @ 0x0000000012669bd8 in /usr/bin/clickhouse
2024-02-06 15:11:23 3. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000112e6eb0 in /usr/bin/clickhouse
2024-02-06 15:11:23 4. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x00000000112e63fc in /usr/bin/clickhouse
2024-02-06 15:11:23 5. DB::TCPHandler::runImpl() @ 0x0000000011f4abdc in /usr/bin/clickhouse
2024-02-06 15:11:23 6. DB::TCPHandler::run() @ 0x0000000011f5bfc8 in /usr/bin/clickhouse
2024-02-06 15:11:23 7. Poco::Net::TCPServerConnection::start() @ 0x0000000014462e44 in /usr/bin/clickhouse
2024-02-06 15:11:23 8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014464360 in /usr/bin/clickhouse
2024-02-06 15:11:23 9. Poco::PooledThread::run() @ 0x00000000145a3b7c in /usr/bin/clickhouse
2024-02-06 15:11:23 10. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000145a1d24 in /usr/bin/clickhouse
2024-02-06 15:11:23 11. start_thread @ 0x0000000000007624 in /lib/libpthread.so.0
2024-02-06 15:11:23 12. ? @ 0x00000000000d149c in /lib/libc.so.6
```

**Comment by LHLHLHE** [comment]
@jayvynl

**Comment by jayvynl** [comment]
python manage.py help sqlmigrate

**Comment by LHLHLHE** [comment]
Sorry, I forgot to apply the `--database` flag when I used this command, so I didn't see any queries for my clickhouse database.
