### ISSUE TITLE
[BUG] Can't save the data with "where ***"

### ISSUE THREAD

**Issue by lyi61pd** [jayvynl/django-clickhouse-backend#99]
```
test=Vul.objects.filter(id=1).get()
test.a="where **"
test.save()
```
and i get these error
```
Traceback (most recent call last):
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 111, in execute
    response = execute(
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/driver/client.py", line 53, in execute
    rv = self.process_ordinary_query(
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 213, in receive_result
    return result.get_result()
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
    packet = self.receive_packet()
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 62.
DB::Exception: Syntax error: failed at position 56 ('', "Name_Zh" = ''): ', "Name_Zh" = 'Write-what-where Condition' WHERE "CWE_id" = 'CWE-123'. Expected one of: token, Comma, Arrow, Dot, UUID, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7f14982c0609 in ?
11. clone @ 0x7f14981e7293 in ?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/driver/connection.py", line 99, in execute
    super().execute(f"select count(*) from {table} where {where}")
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 117, in execute
    raise OperationalError(orig)
clickhouse_driver.dbapi.errors.OperationalError: Code: 62.
DB::Exception: Syntax error: failed at position 56 ('', "Name_Zh" = ''): ', "Name_Zh" = 'Write-what-where Condition' WHERE "CWE_id" = 'CWE-123'. Expected one of: token, Comma, Arrow, Dot, UUID, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7f14982c0609 in ?
11. clone @ 0x7f14981e7293 in ?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pudding/pud/vul.uniontech.com/vul/apps/cveinfo/crontabs.py", line 92, in update_cwe_info
    cwe_info_obj.save()
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/models/base.py", line 60, in _do_update
    return filtered._update(values) > 0
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/driver/connection.py", line 99, in execute
    super().execute(f"select count(*) from {table} where {where}")
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 117, in execute
    raise OperationalError(orig)
django.db.utils.OperationalError: Code: 62.
DB::Exception: Syntax error: failed at position 56 ('', "Name_Zh" = ''): ', "Name_Zh" = 'Write-what-where Condition' WHERE "CWE_id" = 'CWE-123'. Expected one of: token, Comma, Arrow, Dot, UUID, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7f14982c0609 in ?
11. clone @ 0x7f14981e7293 in ?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 111, in execute
    response = execute(
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/driver/client.py", line 53, in execute
    rv = self.process_ordinary_query(
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 213, in receive_result
    return result.get_result()
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
    packet = self.receive_packet()
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 62.
DB::Exception: Syntax error: failed at position 64 ('UsmartAndroid'): UsmartAndroid', "architecture" = 'arm64', "vul_name" = NULL, "score" = '6.5', "status" = 'unprocessed', "vul_category" = NULL, "description" = NULL, "pub_time" . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7f14982c0609 in ?
11. clone @ 0x7f14981e7293 in ?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/driver/connection.py", line 99, in execute
    super().execute(f"select count(*) from {table} where {where}")
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 117, in execute
    raise OperationalError(orig)
clickhouse_driver.dbapi.errors.OperationalError: Code: 62.
DB::Exception: Syntax error: failed at position 64 ('UsmartAndroid'): UsmartAndroid', "architecture" = 'arm64', "vul_name" = NULL, "score" = '6.5', "status" = 'unprocessed', "vul_category" = NULL, "description" = NULL, "pub_time" . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7f14982c0609 in ?
11. clone @ 0x7f14981e7293 in ?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/models/base.py", line 60, in _do_update
    return filtered._update(values) > 0
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_backend/driver/connection.py", line 99, in execute
    super().execute(f"select count(*) from {table} where {where}")
  File "/home/pudding/software/miniforge3/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 117, in execute
    raise OperationalError(orig)
django.db.utils.OperationalError: Code: 62.
DB::Exception: Syntax error: failed at position 64 ('UsmartAndroid'): UsmartAndroid', "architecture" = 'arm64', "vul_name" = NULL, "score" = '6.5', "status" = 'unprocessed', "vul_category" = NULL, "description" = NULL, "pub_time" . Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x14d642bf in /usr/bin/clickhouse
2. ? @ 0x13d121f0 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
10. ? @ 0x7f14982c0609 in ?
11. clone @ 0x7f14981e7293 in ?
```

i noticed that the problem is its not support for the data format like "where **"

**Comment by lyi61pd** [comment]
and i try to print the sql its like this 
```
ALTER TABLE "cveinfo_cwe_info" UPDATE "Name_En" = Write-what-where Condition WHERE "CWE_id" = CWE-123
```

**Comment by jayvynl** [comment]
Thank you, I will fix soon.

**Comment by lyi61pd** [comment]
thanks!
